# Create an user
POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json

{
    "email": "agente.carpincho@gmail.com",
    "password": "123456",
    "name": "Agente Carpincho",
    "codename": "carpincho"
}

###

POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json

{
    "email": "agente.yaguarete@gmail.com",
    "password": "123456",
    "name": "Agente Yaguarete",
    "codename": "yaguarete"
}

###
